name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install clj
      run: sudo apt install clojure
    - name: Run tests
      run: clj -M:test
